
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: aliamrah
  password: 714534169
  host: localhost
  
development:
  <<: *default
  database: rails_with_react_development

  
test:
  <<: *default
  database: rails_with_react_test

production:
  <<: *default
  database: rails_with_react_production
  username: rails_with_react
  password: <%= ENV['RAILS_WITH_REACT_DATABASE_PASSWORD'] %>
